/** UnitFlow style: preferences are local controls, clearly explained and immediately applied. */
import { Calculator, Moon, RotateCcw, Sun, MonitorCog } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "../components/PageHeader";
import { useUnitFlow } from "../contexts/UnitFlowContext";

export default function Settings() {
  const { settings, updateSettings } = useUnitFlow();
  const setTheme = (theme) => { updateSettings({ theme }); toast.success(`Theme set to ${theme}`); };
  return <div className="page-wrapper page-enter"><PageHeader eyebrow="PREFERENCES" title="Settings" description="Tune your local UnitFlow workspace. Changes are saved only in this browser." /><section className="settings-panel"><div className="settings-heading"><div><p className="eyebrow">APPEARANCE</p><h2>Choose your working surface</h2></div><p>System follows your device’s colour preference.</p></div><div className="theme-choices">{[["light", Sun, "Light", "Warm ivory surface"], ["system", MonitorCog, "System", "Match this device"], ["dark", Moon, "Dark", "Charcoal & moss field"]].map(([value, Icon, label, description]) => <button type="button" key={value} className={settings.theme === value ? "theme-choice is-selected" : "theme-choice"} onClick={() => setTheme(value)}><Icon size={19} /><strong>{label}</strong><small>{description}</small></button>)}</div></section><section className="settings-panel"><div className="settings-heading"><div><p className="eyebrow">NUMBER OUTPUT</p><h2>Result precision</h2></div><p>Automatic trims unnecessary trailing zeroes.</p></div><div className="precision-row"><label htmlFor="precision-select">Decimal precision</label><select id="precision-select" value={settings.precision} onChange={(event) => updateSettings({ precision: event.target.value })}><option value="auto">Auto precision</option><option value="2">2 decimals</option><option value="4">4 decimals</option><option value="6">6 decimals</option><option value="8">8 decimals</option></select></div></section><section className="settings-panel"><div className="settings-heading"><div><p className="eyebrow">INPUT MODE</p><h2>Enable the calculator</h2></div><p>Use safe arithmetic expressions before converting a value.</p></div><button type="button" className={settings.calculatorMode ? "toggle-row is-on" : "toggle-row"} onClick={() => { updateSettings({ calculatorMode: !settings.calculatorMode }); toast.success(settings.calculatorMode ? "Calculator mode disabled" : "Calculator mode enabled"); }} aria-pressed={settings.calculatorMode}><span className="toggle-icon"><Calculator size={17} /></span><span><strong>Calculator mode</strong><small>Accepts +, −, ×, ÷, and parentheses without executing code.</small></span><i className="toggle-track"><b /></i></button></section><section className="privacy-panel"><RotateCcw size={20} /><div><strong>Local-first by design</strong><p>History, saved pairs, output precision, and theme preferences are stored in this browser. UnitFlow does not create an account or send your measurements to a server.</p></div></section></div>;
}
